version: "3"

services:

  notebook-samples-test:
    container_name: notebook-samples
    image: finbourne/notebook-runner2:latest
    environment:
      - FBN_LUSID_API_URL=${FBN_BASE_API_URL}/api
      - FBN_LUMI_API_URL=${FBN_BASE_API_URL}/honeycomb
      - FBN_ACCESS_TOKEN

      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_SECRETS_PATH
    volumes:
      - .:/usr/notebooks
    entrypoint: /bin/bash
    command:
      - -ce
      - |
        pip config set global.disable-pip-version-check true
        export FBN_NOTEBOOK_FOLDER=/usr/notebooks
        cd $${FBN_NOTEBOOK_FOLDER}
        pip install -r requirements.txt
        python /usr/src/nbrunner.py --notebooks $${FBN_NOTEBOOK_FOLDER}/examples
        python /usr/src/nbrunner.py --notebooks $${FBN_NOTEBOOK_FOLDER}/university
